spring:
  application:
    name: tmxk-service
  config:
    import: "nacos:${spring.application.name}.yaml?group=prod&refreshEnabled=true"
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_HOST:127.0.0.1}:${NACOS_SERVER_PORT:8848}
        file-extension: yaml